---
# Source: keycloak/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgresql
  namespace: "keycloak"
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-14.2.0
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  postgres-password: "T3dGNlI3RVVVSg=="
  password: "a2V5Y2xvYWsxMjM0NQ=="
  #password: "aHIwZDg1OEJOalI3VXk1WWswCg=="
  # We don't auto-generate LDAP password when it's not provided as we do for other passwords
